### ISSUE TITLE
KeyError: 'construct_reaction'

### ISSUE THREAD

**Issue by hyunwhanjoe** [arbasher/prepBioCyc#2]
I passed the --build-indicator option and I get a KeyError for 'construct_reaction' in the file parse_biocyc.py line 70. I looked at the source code and it seems that arg.construct_reaction is not defined in main.py causing the KeyError. I also think arg.use_ec and arg.map_all are also not defined and would lead to KeyErrors.

**Comment by arbasher** [comment]
I updated the module. Please check and inform me if you encounter any errors. Thank you!

**Comment by hyunwhanjoe** [comment]
Thank you for the update.
